let skip_defaults_vim=1
set nocompatible

" autoindent new lines
set autoindent

" show line numbers
set number

" col and row info on bottom right
set ruler

" show command insert mode
set showmode

set tabstop=2

set softtabstop=2
set shiftwidth=2
set smartindent
set smarttab

if v:version >= 800
  set nofixendofline
endif

" replace tabs with spaces
set expandtab

set textwidth=72

set norelativenumber

set nobackup
set noswapfile
set nowritebackup

set icon

set laststatus=2

syntax enable

set ttyfast

filetype plugin on

if v:version >= 800 && executable('curl') && empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

call plug#begin('~/.vimplugins')
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'
Plug 'https://github.com/joshdick/onedark.vim.git'
Plug 'sheerun/vim-polyglot'
call plug#end()

colorscheme onedark
