vim.opt.number = true
vim.opt.showmode = true
vim.opt.showcmd = true
vim.opt.hlsearch = false
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.writebackup = false
vim.opt.errorbells = false
vim.opt.smartindent = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.smarttab = true
vim.opt.expandtab = true
vim.opt.incsearch = true
vim.opt.termguicolors = true
vim.opt.scrolloff = 20
vim.opt.signcolumn = 'yes'
vim.opt.cmdheight = 1
vim.opt.hidden = true
vim.opt.shortmess = vim.o.shortmess .. 'c'
vim.opt.updatetime = 50
vim.opt.wildignore = vim.o.wildignore .. '*/tmp/*'
vim.opt.wildignore = vim.o.wildignore .. '*/vendor/*'
vim.opt.wildignore = vim.o.wildignore .. '*/node_modules/*'
vim.opt.wildmenu = true
vim.opt.list = true
vim.opt.listchars = 'tab:  ,eol:↲'
vim.opt.completeopt = 'menu,menuone,noselect'
vim.opt.splitright = true
vim.opt.clipboard = "unnamedplus"

