#!/bin/sh

project=$(tmuxinator list -n |
    tail -n +2 |
    fzf --no-multi --preview-window=right:hidden --prompt="Project: " -m -1 -q "$1")

if [ -z "$project" ]; then
    return 0;
fi
tmuxinator start "$project"
