#!/bin/sh

project=$(tmuxinator list -n |
    tail -n +2 |
    fzf --no-multi --preview-window=right:hidden --prompt="Project: " -m -1 -q "$1")

if [ -z "$project" ]; then
    return 0;
fi
tmuxinator start "$project" --no-attach

if [ -n "$TMUX" ]; then
    session=$(tmux list-sessions -F "#S" | fzf --prompt="Session: ")
    if [ -n "$session" ]; then
        tmux switch-client -t "$session"
    fi
else
    tmux attach-session
fi
