vim.o.hlsearch = false
vim.o.number = true
vim.o.mouse = 'a'
vim.o.showmode = true
vim.o.clipboard = "unnamedplus"
vim.o.breakindent = true
vim.o.undofile = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.wo.signcolumn = 'yes'
vim.o.updatetime = 250
vim.o.timeout = true
vim.o.timeoutlen = 300
vim.o.completeopt = 'menuone,noselect'
vim.o.termguicolors = true
vim.o.splitright = true
vim.o.showcmd = true
vim.o.errorbells = false
vim.o.incsearch = true
vim.o.scrolloff = 10
vim.o.list = true
vim.o.listchars = 'tab:  ,eol:↲'
vim.o.cmdheight = 1
vim.o.swapfile = false

vim.o.smartindent = true
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.smarttab = true
vim.o.expandtab = true

-- vim.o.shortmess = vim.o.shortmess .. 'c'
-- vim.o.wildignore = vim.o.wildignore .. '*/tmp/*'
-- vim.o.wildignore = vim.o.wildignore .. '*/vendor/*'
-- vim.o.wildignore = vim.o.wildignore .. '*/node_modules/*'
