# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

HYPHEN_INSENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"

plugins=(
    brew
    fd
    fzf
    gh
    git
    httpie
    nvm
    ripgrep
    tmux
    tmuxinator
)

source $ZSH/oh-my-zsh.sh

typeset -U path

BREW_PREFIX=$(brew --prefix)

path=(
  $BREW_PREFIX/opt/sqlite/bin
  $path
)

export EDITOR=vim
export GIT_EDITOR=vim

export DOTFILES="$HOME/dotfiles"
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG='p:preview-tui'

alias vim="nvim"
alias v="nvim"
alias copy="xclip -selection clipboard"
alias paste="xclip -o -selection clipboard"
alias cat="bat"
alias dotfiles="cd $DOTFILES"

n () {
  if [[ "${NNNLVL:-0}" -ge 1 ]]; then
    echo "nnn is already running"
    return
  fi

  # Use export to ALWAYS cd on quit, otherwise its goind to cd on ^G
  NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
  # export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

  \nnn "$@"

  if [ -f "$NNN_TMPFILE" ]; then
    . "$NNN_TMPFILE"
    rm -f "$NNN_TMPFILE" > /dev/null
  fi
}
